config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users

  root 'posts#index'

  post 'login' => 'users#login'
  post 'logout' => 'users#logout'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :current_action

  before_action :authorize
  after_action :cache_redirected_action

  private
  def current_user
    User.find_by_id(session[:current_user_id])
  end

  def login_user(user)
    session[:current_user_id] = user.id
  end

  def current_action
    [current_user.try(:role) || 'anonymous', controller_name, action_name]
  end

  def authorize
    seq = Rails.configuration.privileges[current_action]
    if seq.last == :mismatch
      flash.now[:error] = "You're not authorized to do this action."
      render "layouts/401", status: :unauthorized
    end
  end

  def cache_redirected_action
    session[:redirected_action] = if response.status == 302
                                    current_action
                                  end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.merge(user: current_user))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def login
    msg = if u = User.find_by(name: params[:name])
            login_user(u)
            "Welcome back"
          else
            "Unknown user name: #{params[:name]}"
          end
    redirect_to root_path, notice: msg
  end

  def logout
    session[:current_user_id] = nil
    redirect_to root_path, notice: "Bye."
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        if current_user.nil?
          login_user(@user)
        end

        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:role, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/401.html.erb
<%= link_to 'Back', posts_path %>

app/views/layouts/_login.html.erb
<div class="u-cf header">
  <div class="u-pull-right">
    <% if current_user %>
    <h5>
      <%= current_user.name %> (<%= current_user.role %>)
      <%= form_tag('/logout', style: 'display: inline') do |f| %>
      <%= submit_tag 'Logout' %>
      <% end %>
    </h5>
    <% else %>
    <%= form_tag('/login') do |f| %>
    <%= text_field_tag :name, '', :placeholder => "Name" %>
    <%= submit_tag 'Login', class: "button-primary" %>
    <%= link_to 'Sign Up', new_user_path, class: "button" %>
    <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_matching.html.erb
<div class="authorization">
  <% matching = Rails.configuration.privileges[action] %>
  <pre><code>current_action => <%= action %> <%= "(before redirected)" if redirected %>
matching = privileges[current_action] => <%= matching.inspect %>
matching.last == :match => <%= matching.last == :match ? "true (Authorized)" : "false (Unauthorized)" %></code></pre>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PieceBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- .container is main centered wrapper -->
<div class="container">
  <div class="row">
    <div class="rules">
      privileges = Piece.load(<a href="javascript:$('#rd').toggle()">File.read(Rails.root.join('config', 'privileges.yml'))</a>)
      <div id="rd" style="display: none">
      <pre><code><%= Rails.configuration.privileges_yml %></code></pre>
      </div>
      <% if session[:redirected_action] %>
      <%= render partial: 'layouts/matching', locals: { action:
      session[:redirected_action], redirected: true } %>
      <% end %>
      <%= render partial: 'layouts/matching', locals: { action:
          current_action, redirected: false } %>
    </div>
  </div>
  <div class="row">
    <%= render partial: 'layouts/login' %>
    <% if flash[:error] %>
    <div class="error">
      <%= flash[:error] %>
    </div>
    <% end %>
    <% if flash[:notice] %>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
    <% end %>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="u-cf">
  <div class="u-pull-left"><h5>Posts </h5></div>
  <div class="u-pull-right"><%= link_to "new", new_post_path, class: "button" %></div>
</div>
<ul>
  <% if @posts.empty? %>
  <li>No posts</li>
  <% end %>
  <% @posts.each do |post| %>
  <li>
    <%= link_to post.title, post %> by <%= post.user.try(:name) || "anonymous" %>
  </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.user.try(:name) || 'anonymous' %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role, options_for_select([["admin", "admin"], ["author", "author"]]) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.role %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>